---
- hosts: all
  become: true

  tasks:

  - name: Download and install Docker.
    shell: curl -fsSL get.docker.com -o get-docker.sh && sh get-docker.sh

  - name: Download telegraf rpm
    get_url:
      url: https://dl.influxdata.com/telegraf/releases/telegraf_1.7.2-1_armhf.deb 
      dest: /tmp

  - name: Download RPi drivers
    get_url:
      url: https://www.compulab.com/wp-content/uploads/2018/05/iot-gate-rpi_raspbian_2018-05-13.zip
      dest: /tmp

  - name: Extract RPi drivers
    unarchive:
      src: /tmp/iot-gate-rpi_raspbian_2018-05-13.zip
      dest: /tmp
      remote_src: yes

  - name: Install RPi drivers (1/5)
    apt: 
      deb: /tmp/iot-gate-rpi-raspbian/iot-gate-dt.deb
      state: present

  - name: Install RPi drivers (2/5)
    apt:
      deb: /tmp/iot-gate-rpi-raspbian/iot-gate-eth.deb
      state: present

  - name: Install RPi drivers (3/5)
    apt:
      deb: /tmp/iot-gate-rpi-raspbian/iot-gate-serial.deb
      state: present 

  - name: Install RPi drivers (4/5)
    apt:
      deb: /tmp/iot-gate-rpi-raspbian/rpi3-modem.deb
      state: present

  - name: Install RPi drivers (5/5)
    apt:
      deb: /tmp/iot-gate-rpi-raspbian/rpi3-rtc.deb
      state: present

  - name: Install Telegraf
    apt:
      deb: /tmp/telegraf_1.7.2-1_armhf.deb
      state: present

  - name: Install Python-pip
    apt:
      name: python-pip
      state: latest

  - pip:
      name: docker-py

  - file:
      path: /opt/xom
      owner: iotadmin
      group: docker
      state: directory
      mode: 0777
    become: true

  - systemd:
      name: docker
      state: started
      enabled: True
    become: true
 
  - systemd:
      name: telegraf
      state: started
      enabled: True
    become: true

