---
- hosts: all
  become: true

  tasks:

  - name: Execute the command in remote shell; stdout goes to the specified file on the remote.
    shell: curl -fsSL get.docker.com -o get-docker.sh && sh get-docker.sh

  - name: Download telegraf rpm
    get_url:
      url: https://dl.influxdata.com/telegraf/releases/telegraf_1.7.2-1_armhf.deb 
      dest: /tmp

  - name: Download RPi drivers
    get_url:
      url: https://www.compulab.com/wp-content/uploads/2018/05/iot-gate-rpi_raspbian_2018-05-13.zip
      dest: /tmp

  - name: Extract foo.tgz into /var/lib/foo
    unarchive:
      src: /tmp/iot-gate-rpi_raspbian_2018-05-13.zip
      dest: /tmp/rpi_drivers
      remote_src: yes

  - name: Install Telegraf
    apt:
      deb: /tmp/telegraf_1.7.2-1_armhf.deb
      state: present

  - name: Install Python-pip
    apt:
      name: python-pip
      state: latest

  - pip:
      name: docker-py

  - file:
      path: /opt/xom
      owner: iotadmin
      group: docker
      state: directory
      mode: 0777
    become: true

  - systemd:
      name: docker
      state: started
      enabled: True
    become: true
 
  - systemd:
      name: telegraf
      state: started
      enabled: True
    become: true

