---
- hosts: all
  become: true

  tasks:
  - name: Install Updates
    apt:
      name: "*"
      state: latest  

  - name: Execute the command in remote shell; stdout goes to the specified file on the remote.
    shell: curl -sSL https://get.docker.com | sh


  - name: Install Docker
    yum:
      name: docker
      state: latest
    become: true
  - name: Download telegraf rpm
    get_url:
      url:  https://dl.influxdata.com/telegraf/releases/telegraf_1.7.1-1_armel.deb
      dest: /tmp
  - name: Install Telegraf
    yum:
      name: /tmp/telegraf-1.7.1-1_armel.deb
      state: present

  - name: Copy Telegraf config
    copy:
      src: /home/djhedge/ansible-centos-HPEGL10/telegraf.conf
      dest: /etc/telegraf/telegraf.conf

  - systemd:
      name: docker
      state: started
      enabled: True
    become: true
  - systemd:
      name: telegraf
      state: started
      enabled: True
    become: true
