---
- hosts: all
  become: true

  tasks:

  - name: Execute the command in remote shell; stdout goes to the specified file on the remote.
    shell: curl -fsSL get.docker.com -o get-docker.sh && sh get-docker.sh

  - name: Download telegraf rpm
    get_url:
      url:  https://dl.influxdata.com/telegraf/releases/telegraf_1.7.1-1_armel.deb
      dest: /tmp

  - name: Install Telegraf
    yum:
      name: /tmp/telegraf-1.7.1-1_armel.deb
      state: present

  - systemd:
      name: docker
      state: started
      enabled: True
    become: true
 
  - systemd:
      name: telegraf
      state: started
      enabled: True
    become: true
