---
- hosts: all

  tasks:
  - name: Create Update Folder
    file:
     path: /boot/efi/EFI/update
     state: directory    
    become: yes
    
  - name: Create Update Folder
    file:
     path: /boot/efi/EFI/centos/orig
     state: directory    
    become: yes    
   
  - name: Move grubx64.efi
    command: mv /boot/efi/EFI/centos/grubx64.efi /boot/efi/EFI/centos/orig/grubx64.efi
    ignore_errors: yes
    become: yes
    
  - name: Download BIOS 
    get_url:
      url: https://github.com/itswag7/IoT-Test/raw/master/AMI_BIOS/x86_bios.bin
      dest: /tmp/x86_bios.bin
      checksum: md5:cc3899ed65c3f287bddf9b5c2b5d1b41
    become: yes
    
  - name: Move bios
    command: mv /tmp/x86_bios.bin /boot/efi/EFI/update/x86_bios.bin
    become: yes
    
  - name: Download grubx64.efi 
    get_url:
      url: https://github.com/itswag7/IoT-Test/raw/master/AMI_BIOS/grubx64.efi
      dest: /tmp/grubx64.efi
      checksum: md5:c100999ee5aab596e3a3d60432ab55b8
    become: yes

  - name: Move grubx64
    command: mv /tmp/grubx64.efi /boot/efi/EFI/centos/grubx64.efi
    become: yes

  - name: Download afuefix64.efi  
    get_url:
      url: https://github.com/itswag7/IoT-Test/raw/master/AMI_BIOS/afuefix64.efi
      dest: /tmp/afuefix64.efi
      checksum: md5:c5de6e70f49f67a35c4ee2941a7d4caf
    become: yes
 
  - name: Move afuefix64.efi
    command: mv /tmp/afuefix64.efi /boot/efi/EFI/update/afuefix64.efi
    become: yes
    
  - name: Download startup.nsh  
    get_url:
      url: https://github.com/itswag7/IoT-Test/raw/master/AMI_BIOS/startup.nsh
      dest: /tmp/startup.nsh
      checksum: md5:488b339bc4c8273741b041c5753a29af
    become: yes
    
  - name: Move startup.nsh 
    command: mv /tmp/startup.nsh  /boot/efi/EFI/centos/startup.nsh
    become: yes  
#  - name: Rebooting host
#    shell: 'shutdown -r +1 "Reboot triggered by Ansible"'
#    become: yes

 #- wait_for_connection:
 #   delay: 90
 #   timeout: 600
