---
- hosts: all

  tasks:
    
  - name: Check that the somefile.conf exists
    stat:
      path: /boot/efi/EFI/update
    register: stat_update_result
    become: yes

  - name: Create the file, if it doesnt exist already
    stat:
      path: /boot/efi/EFI/centos/orig
    register: stat_orig_result 
    become: yes

  - name: Create the file, if it doesnt exist already
    stat:
      path: /boot/efi/EFI/centos/orig/grubx64.efi
    register: stat_grubxorig_result
    become: yes

  - name: Create the file, if it doesnt exist already
    stat:
      path: /boot/efi/EFI/centos/startup.nsh
    register: stat_startup_result
    become: yes

  - name: example copying file with owner and permissions
    copy:
      src: /home/djhedge/compulab/bios.bin
      dest: /boot/efi/EFI/update
    become: yes

  - name: Rebooting host
    shell: 'shutdown -r +1 "Reboot triggered by Ansible"'
    become: yes

  - wait_for_connection:
    delay: 90
    timeout: 600
