---
- hosts: 192.168.1.42

  tasks:
  - name: Pull Node-Red
    docker_image:
      name: nodered/node-red-docker
    become: true
  - name: Pull InfluxDB
    docker_image:
      name: influxdb
    become: true
  - name: Start NodeRed
    docker_container:
      name: Nodered
      image: nodered/node-red-docker
      state: started
      ports:
       - "1880:1880"
    become: true
  - name: Start InfluxDB
    docker_container:
      name: Master_influxdb
      image: influxdb
      state: started
      ports:
       - "8086:8086"
      volumes:
       - /var/lib/influxdb
    become: true
