---
- hosts: all

  tasks:
  - file:
      path: /opt/xom/flaremonitor/{{tenant_name}}/src
      state: directory
      mode: 0755

  - file:
      path: /opt/xom/flaremonitor/{{tenant_name}}/out
      state: directory
      mode: 0755

  - name: Pull Flaremonitor
    docker_container:
      name: "{{tenant_name}}"
      image: flaremonitor:1.3
      state: started
      volumes:
       - /opt/xom/flaremonitor/{{tenant_name}}/src
       - /opt/xom/flaremonitor/{{tenant_name}}/out
      command: python /src/flaremonitor.py
    become: true
