---
- hosts: all

  tasks:
  - file:
      path: /opt/xom/flaremonitor/src
      state: directory
      mode: 0755

  - file:
      path: /opt/xom/flaremonitor/out
      state: directory
      mode: 0755

  - name: Pull Flaremonitor
    docker_container:
      name: Master_influxdb
      image: influxdb
      state: started
      volumes:
       - /opt/xom/flaremonitor/src
       - /opt/xom/flaremonitor/out
    become: true
