---
- hosts: all

  tasks:
  - name: Loading IoT Data Simulator
    copy:
      src: /home/djhedge/docker_images/iotdatasim/iotdatasim.tar
      dest: /var/tmp
    become: true
  - name: Run the command if the specified file does not exist.
    command: "docker load -i /var/tmp/iotdatasim.tar"
    become: true
  - name: Start IoT Data Simulator
    docker_container:
      image: iotdatasim
      state: started
    become: true
  - name: Removing existing war
    file:
      path: /var/tmp/iotdatasim.tar
      state: absent
