---
- hosts: all

  tasks:
  - name: Start Deployment
    shell: python test.py
    args:
      chdir: /home/djhedge/pyBusylight/
    async: 450
    poll: 0
  become: true

  - name: Loading IoT Data Simulator
    copy:
      src: /home/djhedge/docker_images/iotdatasim/iotdatasim.tar
      dest: /tmp
  - name: Importing IoT Data Simulator into local docker repo.
    command: "docker load -i /tmp/iotdatasim.tar"
  - name: Start IoT Data Simulator
    docker_container:
      image: iotdatasim
      name: IoTDataSimx86
      state: started
  - name: Removing existing war
    file:
      path: /tmp/iotdatasim.tar
      state: absent


  - name: Finish Deployment
    shell: python done.py
    args:
      chdir: /home/djhedge/pyBusylight/
    async: 450
    poll: 0
  become: true
