---
- hosts: all

  tasks:
  - name: Pull Kerberos Video
    docker_image:
      name: kerberos/kerberos

  - name: CopyXOM Wifi
    copy:
      src: /home/djhedge/git_repo_prod/kerberos_configs/
      dest: /tmp
      become: true
 
  - name: Start Kerberos
    docker_container:
      name: Kerberos_Cam
      image: kerberos/kerberos
      state: started
      ports:
       - "80:80"
       - "8889:8889"

