---
- hosts: all

  tasks:
  - name: Pull Kerberos Video
    docker_image:
      name: kerberos/kerberos

  - name: Copy Video Configs
    copy:
      src: /home/djhedge/git_repo_prod/kerberos_configs
      dest: /var/tmp
    become: true
 
  - name: Start Kerberos
    docker_container:
      name: Kerberos_Cam
      image: kerberos/kerberos
      state: started
      ports:
       - "80:80"
       - "8889:8889"
      volumes:
       - "/var/tmp/kerberos_config:/etc/opt/kerberosio/config:ro"
