---
- hosts: all

  tasks:
  - name: Pull Kerberos Video
    docker_image:
      name: kerberos/kerberos

  - name: Create Kerberos directory
    file:
      path: /opt/xom/kerberos/{{tenant_name_camera}}/configs
      state: directory
 
  - name: Start Kerberos
    docker_container:
      name: "{{ tenant_name_camera }}"
      image: kerberos/kerberos
      state: started
      ports:
       - "80:80"
       - "8889:8889"
      volumes:
       - "/opt/xom/kerberos/{{tenant_name_camera}}/configs:/etc/opt/kerberosio/config"
