---
- hosts: all

  tasks:
  - name: Update all packages
    yum: name=* state=latest
    become: true

  - name: Install epel-release
    yum:
      name: epel-release
      state: latest
    become: true

  - name: Install Openvpn
    yum:
      name: openvpn
      state: latest
    become: true

