---
- hosts: all

  tasks:
  - name: Start Deployment
    shell: python test.py
    args:
      chdir: /home/djhedge/pyBusylight/
    async: 450
    poll: 0
  become: true

  - name: Finish Deployment
    shell: python done.py
    args:
      chdir: /home/djhedge/pyBusylight/
    async: 45
    poll: 0
  become: true
