---
- hosts: all

  tasks:
  - name: Update all packages
    yum: name=* state=latest
    become: true

  - name: Install Docker reqs
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    become: true

  - name: Add docker repository
    yum_repository:
      name: docker-ce-stable
      description: Docker repo
      baseurl: https://download.docker.com/linux/centos/docker-ce.repo
    become: true

  - name: Install docker
    yum:
      name: docker-ce
      state: latest
    become: true

  - name: Install epel-release
    yum:
      name: epel-release
      state: latest
    become: true

  - name: Install Python-pip
    yum:
      name: python-pip
      state: latest
    become: true

  - pip:
      name: docker-py
    become: true

  - file:
      path: /opt/xom
      owner: iotadmin
      group: docker
      state: directory
      mode: 0777
    become: true

  - name: Download telegraf rpm
    get_url:
      url:  https://dl.influxdata.com/telegraf/releases/telegraf-1.7.0-1.x86_64.rpm
      dest: /tmp

  - name: Install Telegraf
    yum:
      name: /tmp/telegraf-1.7.0-1.x86_64.rpm
      state: present
    become: true

  - systemd:
      name: docker
      state: started
      enabled: True
    become: true

  - systemd:
      name: telegraf
      state: started
      enabled: True
    become: true
